### ISSUE TITLE
Display problem for large inputs

### ISSUE THREAD

**Issue by jimroll** [BGSU-RNA/JAR3D-Website#7]
When JAR3D is given a "large" input (many sequences for a single loop or a long RNA with multiple loops) the data initially displayed is often incorrect.  It pulls the wrong rows from the database, and does not always pull 10.  Waiting for a while and refreshing the page fixes the issue.  The correct information is in the database.  This is happening on jar3d production and dev.

**Comment by AntonPetrov** [comment]
I'm closing this issue because it has been inactive for a while.
